import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

  export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sr">
      <body className="antialiased">
        <header>
          <nav className="flex justify-between items-center p-6 bg-white shadow-sm border-b">
            {/* Logo koji vodi na početnu */}
            <Link href="/" className="text-2xl font-serif font-bold text-pink-600">
              Salon Lepote ✨
            </Link>

            {/* Linkovi */}
            <div className="flex gap-8">
              <Link 
                href="/" 
                className="text-gray-700 hover:text-pink-500 transition font-medium"
              >
                Početna
              </Link>
              
              <Link 
                href="/kontakt" 
                className="text-gray-700 hover:text-pink-500 transition font-medium"
              >
                Kontakt
              </Link>
            </div>
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
